config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: true
  workdir: ~/.config/dotdrop
  link_on_import: nolink
  minversion: 0.31.0
actions:
  pre:
    spacevim-install: curl -sLf https://spacevim.org/install.sh | bash
dynvariables:
  os_name: uname
dotfiles:
  f_alias:
    dst: ~/.alias
    src: alias
  f_bash_profile:
    dst: ~/.bash_profile
    src: bash_profile
  f_env:
    dst: ~/.env
    src: env
  f_functions:
    dst: ~/.functions
    src: functions
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_init.toml:
    dst: ~/.SpaceVim.d/init.toml
    src: SpaceVim.d/init.toml
  f_matplotlibrc:
    dst: ~/.matplotlib/matplotlibrc
    src: matplotlib/matplotlibrc
  f_richban.zsh-theme:
    dst: ~/.oh-my-zsh/custom/themes/richban.zsh-theme
    src: oh-my-zsh/custom/themes/richban.zsh-theme
  f_settings.json:
    dst: ~/.vscode/settings.json
    src: vscode/settings.json
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_tmux.conf.local:
    dst: ~/.tmux.conf.local
    src: tmux.conf.local
  f_tmuxinator.zsh:
    dst: ~/tmuxinator.zsh
    src: tmuxinator.zsh
  f_tool-versions:
    dst: ~/.tool-versions
    src: tool-versions
  f_zshenv:
    dst: ~/.zshenv
    src: zshenv
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  f_ghostwheel.zsh-theme:
    src: oh-my-zsh/custom/themes/ghostwheel.zsh-theme
    dst: ~/.oh-my-zsh/custom/themes/ghostwheel.zsh-theme
  f_iterm-profile.json:
    src: iterm-profile.json
    dst: ~/.iterm-profile.json
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_init.lua:
    src: hammerspoon/init.lua
    dst: ~/.hammerspoon/init.lua
  f_shortcuts.lua:
    src: hammerspoon/shortcuts.lua
    dst: ~/.hammerspoon/shortcuts.lua
  f_utils.lua:
    src: hammerspoon/utils.lua
    dst: ~/.hammerspoon/utils.lua
  f_skhdrc:
    src: skhdrc
    dst: ~/.skhdrc
  f_yabairc:
    src: yabairc
    dst: ~/.yabairc
  f_yank.sh:
    src: yank.sh
    dst: ~/yank.sh
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_yank.vim:
    src: vim/autoload/yank.vim
    dst: ~/.vim/autoload/yank.vim
  f_ayu.vim:
    src: vim/colors/ayu.vim
    dst: ~/.vim/colors/ayu.vim
  f_typescript.vim:
    src: vim/compiler/typescript.vim
    dst: ~/.vim/compiler/typescript.vim
  f_typescipt.vim:
    src: vim/ftplugin/typescipt.vim
    dst: ~/.vim/ftplugin/typescipt.vim
  f_sshknownhosts.vim:
    src: vim/syntax/sshknownhosts.vim
    dst: ~/.vim/syntax/sshknownhosts.vim
  f_plugin_yank.vim:
    src: vim/plugin/yank.vim
    dst: ~/.vim/plugin/yank.vim
  f_plug.vim:
    src: vim/autoload/plug.vim
    dst: ~/.vim/autoload/plug.vim
  f_filetype.vim:
    src: vim/filetype.vim
    dst: ~/.vim/filetype.vim
  vim:
    src: vim
    dst: ~/.vim/
    link: link_children
profiles:
  richban-macbook:
    dotfiles:
    - f_init.toml
    - f_tmux.conf
    - f_zshrc
    - f_zshenv
    - f_bash_profile
    - f_env
    - f_alias
    - f_functions
    - f_tool-versions
    - f_tmux.conf.local
    - f_matplotlibrc
    - f_richban.zsh-theme
    - f_gitconfig
    - f_settings.json
    - f_iterm-profile.json
    - f_bashrc
    - f_init.lua
    - f_shortcuts.lua
    - f_utils.lua
    - f_skhdrc
    - f_yabairc
    - f_yank.sh
    - f_p10k.zsh
    - f_vimrc
    - f_yank.vim
    - f_ayu.vim
    - f_typescript.vim
    - f_typescipt.vim
    - f_sshknownhosts.vim
    - f_plugin_yank.vim
    - f_plug.vim
    - f_filetype.vim
  linux:
    dotfiles:
    - f_tmux.conf
    - f_tmux.conf.local
    - f_alias
    - vim
    - f_vimrc

  # Installs Spacevim and dotfiles
  spacevim:
    dotfiles:
    - f_init.toml
    actions:
    - spacevim-install
  alias:
    dotfiles:
    - f_alias
