config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_by_default: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_alias:
    dst: ~/.alias
    src: alias
  f_bash_profile:
    dst: ~/.bash_profile
    src: bash_profile
  f_env:
    dst: ~/.env
    src: env
  f_functions:
    dst: ~/.functions
    src: functions
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_init.toml:
    dst: ~/.SpaceVim.d/init.toml
    src: SpaceVim.d/init.toml
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_tmuxinator.zsh:
    dst: ~/tmuxinator.zsh
    src: tmuxinator.zsh
  f_zshenv:
    dst: ~/.zshenv
    src: zshenv
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  richban-macbook:
    dotfiles:
    - f_init.toml
    - f_tmux.conf
    - f_zshrc
    - f_zshenv
    - f_bash_profile
    - f_env
    - f_alias
    - f_functions
