config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: true
  workdir: ~/.config/dotdrop
  link_on_import: nolink
  minversion: 0.31.0
dynvariables:
  os_name: uname
dotfiles:
  f_alias:
    dst: ~/.alias
    src: alias
  f_functions:
    dst: ~/.functions
    src: functions
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_matplotlibrc:
    dst: ~/.matplotlib/matplotlibrc
    src: matplotlib/matplotlibrc
  f_settings.json:
    dst: ~/.vscode/settings.json
    src: vscode/settings.json
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_tool-versions:
    dst: ~/.tool-versions
    src: tool-versions
  f_zshenv:
    dst: ~/.zshenv
    src: zshenv
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  f_init.lua:
    src: hammerspoon/init.lua
    dst: ~/.hammerspoon/init.lua
  f_shortcuts.lua:
    src: hammerspoon/shortcuts.lua
    dst: ~/.hammerspoon/shortcuts.lua
  f_utils.lua:
    src: hammerspoon/utils.lua
    dst: ~/.hammerspoon/utils.lua
  f_skhdrc:
    src: skhdrc
    dst: ~/.skhdrc
  f_yabairc:
    src: yabairc
    dst: ~/.yabairc
  f_yank.sh:
    src: yank.sh
    dst: ~/yank.sh
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_yank.vim:
    src: vim/autoload/yank.vim
    dst: ~/.vim/autoload/yank.vim
  f_typescript.vim:
    src: vim/compiler/typescript.vim
    dst: ~/.vim/compiler/typescript.vim
  f_typescipt.vim:
    src: vim/ftplugin/typescipt.vim
    dst: ~/.vim/ftplugin/typescipt.vim
  f_sshknownhosts.vim:
    src: vim/syntax/sshknownhosts.vim
    dst: ~/.vim/syntax/sshknownhosts.vim
  f_plugin_yank.vim:
    src: vim/plugin/yank.vim
    dst: ~/.vim/plugin/yank.vim
  f_plug.vim:
    src: vim/autoload/plug.vim
    dst: ~/.vim/autoload/plug.vim
  f_filetype.vim:
    src: vim/filetype.vim
    dst: ~/.vim/filetype.vim
  vim:
    src: vim
    dst: ~/.vim/
    link: link_children
  d_hammerspoon:
    src: hammerspoon
    dst: ~/.hammerspoon
  f_tmux-gruvbox-dark.conf:
    src: tmux/plugins/tmux-gruvbox/tmux-gruvbox-dark.conf
    dst: ~/.tmux/plugins/tmux-gruvbox/tmux-gruvbox-dark.conf
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  f_tmux.remote.conf:
    src: tmux.remote.conf
    dst: ~/.tmux.remote.conf
  f_zshenv_1:
    src: zshenv
    dst: ~/.zshenv
  f_zshrc_1:
    src: zshrc
    dst: ~/.zshrc
  f_user.js:
    src: config/firefox/user.js
    dst: ~/.config/firefox/user.js
    chmod: '600'
  f_gruvbox.itermcolors:
    src: gruvbox.itermcolors
    dst: ~/gruvbox.itermcolors
  f_karabiner.json:
    src: config/karabiner/karabiner.json
    dst: ~/.config/karabiner/karabiner.json
    chmod: '600'
  f_vimium-options.json:
    src: config/firefox/vimium-options.json
    dst: ~/.config/firefox/vimium-options.json
  f_ctags:
    src: ctags
    dst: ~/.ctags
  f_spoof_mac_address.sh:
    src: config/spoof_mac_address.sh
    dst: ~/.config/spoof_mac_address.sh
profiles:
  balthasar-02:
    dotfiles:
    - f_tmux.conf
    - f_zshrc
    - f_zshenv
    - f_alias
    - f_functions
    - f_tool-versions
    - f_matplotlibrc
    - f_gitconfig
    - f_settings.json
    - f_init.lua
    - f_shortcuts.lua
    - f_utils.lua
    - f_skhdrc
    - f_yabairc
    - f_p10k.zsh
    - f_vimrc
    - f_yank.vim
    - f_typescript.vim
    - f_typescipt.vim
    - f_sshknownhosts.vim
    - f_plugin_yank.vim
    - f_plug.vim
    - f_filetype.vim
    - d_hammerspoon
    - f_tmux-gruvbox-dark.conf
    - f_init.vim
    - f_tmux.remote.conf
    - f_user.js
    - f_gruvbox.itermcolors
    - f_karabiner.json
    - f_vimium-options.json
    - f_ctags
    - f_spoof_mac_address.sh
  casper-03:
    dotfiles:
    - f_tmux.conf
    - f_zshrc
    - f_zshenv
    - f_alias
    - f_functions
    - f_tool-versions
    - f_matplotlibrc
    - f_gitconfig
    - f_settings.json
    - f_init.lua
    - f_shortcuts.lua
    - f_utils.lua
    - f_skhdrc
    - f_yabairc
    - f_p10k.zsh
    - f_vimrc
    - f_yank.vim
    - f_typescript.vim
    - f_typescipt.vim
    - f_sshknownhosts.vim
    - f_plugin_yank.vim
    - f_plug.vim
    - f_filetype.vim
    - d_hammerspoon
    - f_tmux-gruvbox-dark.conf
    - f_init.vim
    - f_tmux.remote.conf
    - f_user.js
    - f_gruvbox.itermcolors
    - f_karabiner.json
