config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: true
  workdir: ~/.config/dotdrop
  link_on_import: nolink
  minversion: 0.31.0
dynvariables:
  os_name: uname
dotfiles:
  f_alias:
    dst: ~/.alias
    src: alias
  f_functions:
    dst: ~/.functions
    src: functions
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_matplotlibrc:
    dst: ~/.matplotlib/matplotlibrc
    src: matplotlib/matplotlibrc
  f_settings.json:
    dst: ~/.vscode/settings.json
    src: vscode/settings.json
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_tool-versions:
    dst: ~/.tool-versions
    src: tool-versions
  f_zshenv:
    dst: ~/.zshenv
    src: zshenv
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  f_skhdrc:
    src: skhdrc
    dst: ~/.skhdrc
  f_yabairc:
    src: yabairc
    dst: ~/.yabairc
  f_yank.sh:
    src: yank.sh
    dst: ~/yank.sh
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  d_vim:
    src: vim
    dst: ~/.vim/
    link: link_children
  d_hammerspoon:
    src: hammerspoon
    dst: ~/.hammerspoon
  f_tmux-gruvbox-dark.conf:
    src: tmux/plugins/tmux-gruvbox/tmux-gruvbox-dark.conf
    dst: ~/.tmux/plugins/tmux-gruvbox/tmux-gruvbox-dark.conf
  f_tmux.remote.conf:
    src: tmux.remote.conf
    dst: ~/.tmux.remote.conf
  d_firefox:
    src: config/firefox
    dst: ~/.config/firefox
  d_iterm:
    src: config/iterm
    dst: ~/.config/iterm
  f_karabiner.json:
    src: config/karabiner/karabiner.json
    dst: ~/.config/karabiner/karabiner.json
    chmod: "600"
  f_ctags:
    src: ctags
    dst: ~/.ctags
  f_spoof_mac_address.sh:
    src: config/spoof_mac_address.sh
    dst: ~/.config/spoof_mac_address.sh
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  f_run_pyls_with_venv.sh:
    src: config/run_pyls_with_venv.sh
    dst: ~/.config/run_pyls_with_venv.sh
    chmod: "744"
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_pycodestyle:
    src: config/pycodestyle
    dst: ~/.config/pycodestyle
  f_jupyter_qtconsole_config.py:
    src: jupyter/jupyter_qtconsole_config.py
    dst: ~/.jupyter/jupyter_qtconsole_config.py
  f_ipython_config.py:
    src: ipython/profile_default/ipython_config.py
    dst: ~/.ipython/profile_default/ipython_config.py
profiles:
<<<<<<< HEAD
  balthasar-02:
    dotfiles:
    - f_tmux.conf
    - f_zshrc
    - f_zshenv
    - f_alias
    - f_functions
    - f_tool-versions
    - f_matplotlibrc
    - f_gitconfig
    - f_settings.json
    - f_init.lua
    - f_shortcuts.lua
    - f_utils.lua
    - f_skhdrc
    - f_yabairc
    - f_p10k.zsh
    - f_vimrc
    - f_yank.vim
    - f_typescript.vim
    - f_typescipt.vim
    - f_sshknownhosts.vim
    - f_plugin_yank.vim
    - f_plug.vim
    - f_filetype.vim
    - d_hammerspoon
    - f_tmux-gruvbox-dark.conf
    - f_init.vim
    - f_tmux.remote.conf
    - f_user.js
    - f_gruvbox.itermcolors
    - f_karabiner.json
    - f_vimium-options.json
    - f_ctags
    - f_spoof_mac_address.sh
    - f_gitignore
    - f_starship.toml
    - f_plugins.lua
    - d_lua
    - f_nvim_init.lua
    - d_plugin
    - f_run_pyls_with_venv.sh
    - d_nvim
    - f_pycodestyle
    - f_jupyter_qtconsole_config.py
    - f_ipython_config.py
||||||| parent of a885077 (Update)
  balthasar-02:
    dotfiles:
    - f_tmux.conf
    - f_zshrc
    - f_zshenv
    - f_alias
    - f_functions
    - f_tool-versions
    - f_matplotlibrc
    - f_gitconfig
    - f_settings.json
    - f_init.lua
    - f_shortcuts.lua
    - f_utils.lua
    - f_skhdrc
    - f_yabairc
    - f_p10k.zsh
    - f_vimrc
    - f_yank.vim
    - f_typescript.vim
    - f_typescipt.vim
    - f_sshknownhosts.vim
    - f_plugin_yank.vim
    - f_plug.vim
    - f_filetype.vim
    - d_hammerspoon
    - f_tmux-gruvbox-dark.conf
    - f_init.vim
    - f_tmux.remote.conf
    - f_user.js
    - f_gruvbox.itermcolors
    - f_karabiner.json
    - f_vimium-options.json
    - f_ctags
    - f_spoof_mac_address.sh
    - f_gitignore
    - f_starship.toml
    - f_plugins.lua
    - d_lua
    - f_nvim_init.lua
    - d_plugin
    - f_run_pyls_with_venv.sh
    - d_nvim
=======
>>>>>>> a885077 (Update)
  casper-03:
    dotfiles:
      - f_tmux.conf
      - f_zshrc
      - f_zshenv
      - f_alias
      - f_functions
      - f_tool-versions
      - f_matplotlibrc
      - f_gitconfig
      - f_settings.json
      - f_skhdrc
      - f_yabairc
      - f_vimrc
      - f_tmux-gruvbox-dark.conf
      - f_init.vim
      - f_tmux.remote.conf
      - f_karabiner.json
      - f_ctags
      - f_spoof_mac_address.sh
      - f_gitignore
      - f_starship.toml
      - f_plugins.lua
      - f_run_pyls_with_venv.sh
      - d_nvim
      - d_vim
      - d_firefox
      - d_hammerspoon
      - d_iterm
