config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
  link_on_import: nolink
  minversion: 0.31.0
dotfiles:
  f_alias:
    dst: ~/.alias
    src: alias
  f_bash_profile:
    dst: ~/.bash_profile
    src: bash_profile
  f_env:
    dst: ~/.env
    src: env
  f_functions:
    dst: ~/.functions
    src: functions
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_init.toml:
    dst: ~/.SpaceVim.d/init.toml
    src: SpaceVim.d/init.toml
  f_matplotlibrc:
    dst: ~/.matplotlib/matplotlibrc
    src: matplotlib/matplotlibrc
  f_richban.zsh-theme:
    dst: ~/.oh-my-zsh/custom/themes/richban.zsh-theme
    src: oh-my-zsh/custom/themes/richban.zsh-theme
  f_settings.json:
    dst: ~/.vscode/settings.json
    src: vscode/settings.json
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_tmux.conf.local:
    dst: ~/.tmux.conf.local
    src: tmux.conf.local
  f_tmuxinator.zsh:
    dst: ~/tmuxinator.zsh
    src: tmuxinator.zsh
  f_tool-versions:
    dst: ~/.tool-versions
    src: tool-versions
  f_zshenv:
    dst: ~/.zshenv
    src: zshenv
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  f_ghostwheel.zsh-theme:
    src: oh-my-zsh/custom/themes/ghostwheel.zsh-theme
    dst: ~/.oh-my-zsh/custom/themes/ghostwheel.zsh-theme
  f_iterm-profile.json:
    src: iterm-profile.json
    dst: ~/.iterm-profile.json
profiles:
  richban-macbook:
    dotfiles:
    - f_init.toml
    - f_tmux.conf
    - f_zshrc
    - f_zshenv
    - f_bash_profile
    - f_env
    - f_alias
    - f_functions
    - f_tool-versions
    - f_tmux.conf.local
    - f_matplotlibrc
    - f_richban.zsh-theme
    - f_gitconfig
    - f_settings.json
    - f_ghostwheel.zsh-theme
    - f_iterm-profile.json
  richban-ubuntu:
    dotfiles:
    - f_init.toml
    - f_tmux.conf
    - f_zshrc
    - f_zshenv
    - f_bash_profile
    - f_env
    - f_alias
    - f_functions
    - f_tool-versions
    - f_tmux.conf.local
    - f_matplotlibrc
    - f_richban.zsh-theme
    - f_gitconfig
  debian:
    dotfiles:
    - f_init.toml
    - f_tmux.conf
    - f_tmux.conf.local
    - f_zshrc
    - f_zshenv
    - f_bash_profile
    - f_env
    - f_alias
    - f_functions
    - f_ghostwheel.zsh-theme
